# Generated by Django 6.0.1 on 2026-01-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='catering_menu',
            field=models.TextField(blank=True, help_text='List of catering options available', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='decoration_options',
            field=models.TextField(blank=True, help_text='List of decoration options available', null=True),
        ),
    ]
