# Generated by Django 6.0.1 on 2026-01-30 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppms_app', '0002_venue_catering_menu_venue_decoration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='catering_menu',
            field=models.TextField(blank=True, help_text='Basic catering summary', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='decoration_options',
            field=models.TextField(blank=True, help_text='Basic decoration summary', null=True),
        ),
        migrations.CreateModel(
            name='CateringMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('min_guests', models.IntegerField(default=50)),
                ('max_guests', models.IntegerField(default=500)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_menus', to='ppms_app.venue')),
            ],
        ),
        migrations.CreateModel(
            name='DecorationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('theme', models.CharField(max_length=100)),
                ('includes_items', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoration_packages', to='ppms_app.venue')),
            ],
        ),
        migrations.CreateModel(
            name='DecorationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='decoration_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('decoration_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ppms_app.decorationpackage')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_item_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('catering_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ppms_app.cateringmenu')),
            ],
        ),
    ]
