# Generated by Django 6.0.1 on 2026-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppms_app', '0003_alter_venue_catering_menu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='cateringmenu',
            options={'ordering': ['venue', 'name'], 'verbose_name_plural': 'Catering Menus'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='decorationimage',
            options={'verbose_name_plural': 'Decoration Images'},
        ),
        migrations.AlterModelOptions(
            name='decorationpackage',
            options={'ordering': ['venue', 'name'], 'verbose_name_plural': 'Decoration Packages'},
        ),
        migrations.AlterModelOptions(
            name='menuitemimage',
            options={'verbose_name_plural': 'Menu Item Images'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name_plural': 'Venues'},
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='confirmed', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='event_type',
            field=models.CharField(blank=True, default='Not specified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_catering',
            field=models.CharField(blank=True, default='Not selected', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_catering_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_decoration',
            field=models.CharField(blank=True, default='Not selected', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_decoration_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='decorationpackage',
            name='includes_items',
            field=models.TextField(help_text='Comma-separated list of items included'),
        ),
        migrations.AlterField(
            model_name='decorationpackage',
            name='theme',
            field=models.CharField(help_text='Wedding, Birthday, Corporate, etc.', max_length=100),
        ),
    ]
